version: "3.8"

services:
  ubuntu1:
    build:
      context: ./ubuntu1
    container_name: ubuntu1
    volumes:
      - ./ubuntu1/nginx.conf:/etc/nginx/nginx.conf:ro
      - sshkeys:/tmp/ssh_share
    depends_on:
      - ript
    ports:
      - "80:80"
    networks:
      mynet:
        ipv4_address: 10.2.6.10
  
  ript:
    build:
      context: ./ript
    container_name: ubuntu2
    volumes:
      - ./ript/html:/var/www/html:ro
      - ./ript/backup:/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - sshkeys:/tmp/ssh_share
    networks:
      mynet:
        ipv4_address: 10.2.6.11

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.6.0/24

volumes:
  sshkeys:
